./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
./checkers "java PlayerHelperMason" "java PlayerHelper" 3 >>AB.txt2 2>/dev/null
