./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers "java PlayerHelperMason" d5 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
./checkers d5 "java PlayerHelperMason" 3 >>d5.txt2 2>/dev/null
