./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers "java PlayerHelperMason" diff 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
./checkers diff "java PlayerHelperMason" 3 >>diff.txt2 2>/dev/null
