./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers "java PlayerHelperMason" computer 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
./checkers computer "java PlayerHelperMason" 1 >>random.txt2 2>/dev/null
