./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers "java PlayerHelperMason" rat 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
./checkers rat "java PlayerHelperMason" 3 >>rat.txt 2>/dev/null
